#!/bin/bash
#simulate RPi (dev/test only)
echo "#dummy timing to match dev host:"
echo "dpi_timings=1920 -1522 0 1 0  1080 -781 0 1 0  0 0 0  20 0 2400000 1"
echo "#dummy timing for RPi:"
echo "dpi_timings=398 0 0 1 0  299 0 0 1 0  0 0 0  20 0 2400000 1"
#eof
